services:
  db:
    container_name: db
    image: postgres:16.6
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    container_name: app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/docker_template
    env_file:
      - ../.env
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ./entrypoint.sh